[project]
name = "learn-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Iris Randolph", email = "irandolph@hmc.edu" }
]
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.3",
]

[project.scripts]
learn-pandas = "learn_pandas:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
